name: 'Channel Post'
description: 'Push files to Telegram channel'
author: 'xireiki'
branding:
  icon: 'edit'
  color: 'white'
inputs:
  bot_token:
    description: 'Telegram Bot Token'
    required: true
  chat_id:
    description: 'Telegram Channel/Chat ID'
    required: true
  context:
    description: 'Caption'
    required: false
    default: ''
  path:
    description: 'File Path'
    required: false
  parse_mode:
    description: 'Parse Mode'
    required: false
    default: ''
  method:
    description: 'Occurrence method, default sendDocument'
    required: false
    default: 'sendDocument'
  large_file:
    description: 'Enable large file support, api_id and api_hash are required after enabling'
    required: false
    default: false
  api_id:
    description: 'Telegram Developer api_id'
    required: false
  api_hash:
    description: 'Telegram Developer api_hash'
    required: false
  api_server:
    description: 'Customize the download address of the compiled [telegram-bot-api](https://github.com/tdlib/telegram-bot-api) binary file'
    required: false
  run_cmd:
    description: 'Command to start telegram-bot-api'
    required: false
  api_server_file_name:
    description: 'The filename of the custom telegram-bot-api will replace `${fileName}` in run_cmd'
    required: false
  topic_id:
    description: 'The ID of the super group subtopic'
    required: false
outpuuts:
  msgId:
    description: "msgid of the sent message"
runs:
  using: 'node20'
  main: 'dist/bundle.js'
