name: Test Action

on:
  push:
    paths-ignore:
      - README.md
      - LICENSE
    branches:
      - main
  workflow_dispatch:

jobs:
  test_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Post Info
        id: set-post-info
        run: |
          {
            echo 'CONTEXT<<EOF'
            echo -e "Channel-Post\n\nWorkflow: <a href=\"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\">GitHub</a>\n\ncommit: ${{ github.event.head_commit.message }}"
            echo EOF
          } >> $GITHUB_OUTPUT
          echo path="$GITHUB_WORKSPACE/dist/bundle.js" >> $GITHUB_OUTPUT

      - name: Test Post Document
        uses: ./
        with: 
          chat_id: ${{ secrets.CHAT_ID }}
          bot_token: ${{ secrets.BOT_TOKEN }}
          path: ${{ steps.set-post-info.outputs.path }}
          context: ${{ steps.set-post-info.outputs.CONTEXT }}
          parse_mode: HTML

      - name: Test Post MediaGroup
        uses: ./
        with: 
          chat_id: ${{ secrets.CHAT_ID }}
          bot_token: ${{ secrets.BOT_TOKEN }}
          path: |
            test/*.png
          context: "**Test sendMediaGroup**"
          parse_mode: Markdown
          method: sendMediaGroup

      - name: Generate large files
        run: |
          dd if=/dev/zero of=largefile.img bs=1024k count=55

      - name: Test Post Large File
        uses: ./
        with: 
          chat_id: ${{ secrets.CHAT_ID }}
          bot_token: ${{ secrets.BOT_TOKEN }}
          context: "*Test Post Large File*"
          parse_mode: MarkdownV2
          method: sendFile
          path: "*.img"
          large_file: true
          api_id: ${{ secrets.API_ID }}
          api_hash: ${{ secrets.API_HASH }}

      - name: Test Post Text
        uses: ./
        with: 
          chat_id: ${{ secrets.CHAT_ID }}
          bot_token: ${{ secrets.BOT_TOKEN }}
          context: "**All tests completed**"
          parse_mode: MarkdownV2
          method: sendMessage

  test_darwin:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate large files
        run: |
          dd if=/dev/zero of=largefile.img bs=1024k count=55

      - name: Test Post Large File
        uses: ./
        with: 
          chat_id: ${{ secrets.CHAT_ID }}
          bot_token: ${{ secrets.BOT_TOKEN }}
          context: "*Test Post Large File*"
          parse_mode: MarkdownV2
          method: sendFile
          path: "*.img"
          large_file: true
          api_id: ${{ secrets.API_ID }}
          api_hash: ${{ secrets.API_HASH }}

  test_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate large files
        run: |
          fsutil file createnew largefile.img 57671680

      - name: Test Post Large File
        uses: ./
        with: 
          chat_id: ${{ secrets.CHAT_ID }}
          bot_token: ${{ secrets.BOT_TOKEN }}
          context: "*Test Post Large File*"
          parse_mode: MarkdownV2
          method: sendFile
          path: "*.img"
          large_file: true
          api_id: ${{ secrets.API_ID }}
          api_hash: ${{ secrets.API_HASH }}
